# Generated by Django 4.1.7 on 2023-04-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("json", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_msg_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_msg_id_rel",
                        to="chatbot.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("prime", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("stop", models.CharField(blank=True, max_length=200, null=True)),
                ("default_depth", models.IntegerField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                ("org_id", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "intent_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("intent", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["intent_name"],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sentence", models.TextField(blank=True, null=True)),
                ("sentiment", models.FloatField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "chat_message_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_chat_message_id",
                        to="chatbot.chatmessage",
                    ),
                ),
                (
                    "session_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_session_id",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["chat_message_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                ("token", models.TextField(blank=True, null=True)),
                ("pos", models.TextField(blank=True, null=True)),
                ("dep", models.TextField(blank=True, null=True)),
                ("entity", models.TextField(blank=True, null=True)),
                ("stop_word", models.BooleanField(blank=True, null=True)),
                ("lemma", models.TextField(blank=True, null=True)),
                (
                    "sentence_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_sentence_id",
                        to="chatbot.sentence",
                    ),
                ),
            ],
            options={
                "ordering": ["sentence_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalConfiguration",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("prime", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("stop", models.CharField(blank=True, max_length=200, null=True)),
                ("default_depth", models.IntegerField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                ("org_id", models.CharField(blank=True, max_length=200, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical configuration",
                "verbose_name_plural": "historical configurations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_id",
                to="chatbot.chatsession",
            ),
        ),
    ]
