# Generated by Django 4.1.7 on 2023-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
