# Generated by Django 4.1.7 on 2023-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="interested_as",
            field=models.CharField(
                choices=[
                    ("investor", "Interested as Investor"),
                    ("beta_customer", "Interested as Beta Customer"),
                    ("news", "Interested as News"),
                    ("other", "Interested as Other"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
