# Generated by Django 4.1.7 on 2023-05-14 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_interested_as"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="message",
        ),
    ]
