# Generated by Django 4.1.7 on 2023-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=10)),
                (
                    "app",
                    models.CharField(
                        blank=True, default="app", max_length=255, null=True
                    ),
                ),
                (
                    "logger",
                    models.CharField(
                        blank=True, default="app", max_length=255, null=True
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, default="app", max_length=255, null=True
                    ),
                ),
                (
                    "funcname",
                    models.CharField(
                        blank=True, default="app", max_length=255, null=True
                    ),
                ),
                ("line_no", models.IntegerField(blank=True, null=True)),
                ("message", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
