# Generated by Django 4.1.7 on 2023-04-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("prime", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("stop", models.CharField(blank=True, max_length=200, null=True)),
                ("default_depth", models.IntegerField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                ("org_id", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAIConfiguration",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("prime", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("stop", models.CharField(blank=True, max_length=200, null=True)),
                ("default_depth", models.IntegerField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                ("org_id", models.CharField(blank=True, max_length=200, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ai configuration",
                "verbose_name_plural": "historical ai configurations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("input", models.TextField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("output", models.TextField()),
                ("json", models.JSONField(blank=True, null=True)),
                ("blob", models.BinaryField(blank=True, null=True)),
                (
                    "configuration_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_id",
                        to="core.aiconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
