# Generated by Django 4.1.7 on 2023-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
