# Generated by Django 4.1.7 on 2023-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="alt_image",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
