# Generated by Django 4.1.7 on 2023-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="alt_image",
            field=models.TextField(null=True),
        ),
    ]
