# Generated by Django 4.1.7 on 2023-05-14 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
